name: Build

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure
          dependency-graph: generate
          dependency-graph-continue-on-failure: false

      - name: Build with Gradle
        run: |
          openssl aes-256-cbc -d -in keystore.jks.encrypted -out keystore.jks -k ${{ secrets.ENCRYPTION_KEY }} -A -pbkdf2
          export KEY_STORE="${{ secrets.KEY_STORE }}"
          ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: IFPatcher
          path: build/libs/*.jar
