name: Release

on:
  push:
    tags:
      - "*"

jobs:
  Release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          add-job-summary-as-pr-comment: on-failure
          cache-disabled: true

      - name: Build with Gradle
        run: |
          openssl aes-256-cbc -d -in keystore.jks.encrypted -out keystore.jks -k ${{ secrets.ENCRYPTION_KEY }} -A -pbkdf2
          export KEY_STORE="${{ secrets.KEY_STORE }}"
          ./gradlew build

      - name: Create draft release
        run: gh release create ${{ github.ref_name }} --draft --generate-notes build/libs/*.jar
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Attest build provenance
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: build/libs/*.jar

      - name: Publish release
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ github.token }}
